condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 100
normalize_comments = true
reorder_impl_items = true
spaces_around_ranges = true
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true